### PR TITLE
Modified jquery.facetview.js file to work with BOOTSTRAP-3.x instead of version 2.x

### PR DESCRIPTION
**Pull request by vinayvinay1**
Barely anyone uses Bootstrap 2.x now-a-days. Hence I modified the jquery.facetview.js file to create dynamic HTML content that applies to BOOTSTRAP-3.x definitions.
screen shot 2015-04-23 at 5 39 02 pm

### CODE REVIEW

**Comment by darth-pr** [comment]
Awesome nice update. I also like the remove of the .DS_Store file which is Mac specific.

**Comment by vinayvinay1** [comment]
Thanks for the appreciation Paul.

**Comment by chrismattmann** [comment]
@darth-pr @vinayvinay1 can this be merged pleased?

**Comment by vinayvinay1** [comment]
@chrismattmann  Professor, I think my branch was no longer compatible as there was one more branch by Almoshin that was pulled into the repository which added support for displaying results without title.

@darth-pr  I have made changes to Jquery.facetview.js file to include all the changes that Almoshin pull request had. In other words, I added Bootstrap 3.0 support to your latest version of repository. Feel free to have a look and merge the repository.

**Comment by chrismattmann** [comment]
:+1: @vinayvinay1 @darth-pr please merge

**Comment by chrismattmann** [comment]
@vinayvinay1 @darth-pr can you bring this up to date, please, and merge?

**Comment by chrismattmann** [comment]
ping @vinayvinay1 @darth-pr

**Comment by vinayvinay1** [comment]
@darth-pr  I have verified and this commit works fine if merged. The conflicts are : Bootstrap 2 will be completely removed and upgraded to bootstrap 3.0 .  Please let me know if you need anything from me before you can merge this branch.

**Comment by chrismattmann** [comment]
@vinayvinay1 I think you need to rebase off the latest git:HEAD and then merge into your local branch then push your branch which should resolve the merge conflicts. @darth-pr can you grant me karma on this so I can merge it?

**Comment by chrismattmann** [comment]
thanks, merged this!

**Pull request merged**
